language: go

go:
    - "1.7.1"

env:
    global:
        - SSH_KEY="travis_key"
        - GIT_NAME="Travis CI"
        - GIT_EMAIL="jjafuller@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="master"

before_install:
    - openssl aes-256-cbc -K $encrypted_129c1a48241e_key -iv $encrypted_129c1a48241e_iv -in travis_key.enc -out travis_key -d

before_script:
    - go get -u -v github.com/spf13/hugo

script:
    - git clone https://github.com/spf13/hyde.git ./themes/hyde
    - hugo

after_success:
    - echo "ltcgr.com" > ./public/CNAME
    - ./scripts/deploy.sh