language: go

go:
    - "1.7.1"

env:
    global:
        - SSH_KEY="travis_key"
        - GIT_NAME="Travis CI"
        - GIT_EMAIL="jjafuller@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="src"
        - HUGO_VERSION="0.20.7"

before_install:
    - openssl aes-256-cbc -K $encrypted_129c1a48241e_key -iv $encrypted_129c1a48241e_iv -in travis_key.enc -out travis_key -d

install:
    - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here

before_script:
    - wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    - tar xvzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

script:
    - git clone https://github.com/spf13/hyde.git ./themes/hyde
    - cd ./themes/hyde
    - git checkout 50fec3e32df7b3ef311377db55093fc87bccb446
    - cd ../../
    - ./hugo

after_success:
    - echo "ltcgr.com" > ./public/CNAME
    - bash ./scripts/deploy.sh